version: '3.4'

services:
  codenet.identity.api:
    image: ${DOCKER_REGISTRY-}codenetidentityapi
    container_name: codenet.identity.api
    build:
      context: .
      dockerfile: src/CodeNet.Identity.Api/Dockerfile
    ports:
        - "14000:5000"
        - "14001:5001"

  stoktakip.customer.api:
    image: ${DOCKER_REGISTRY-}stoktakipcustomerapi
    container_name: stoktakip.customer.api
    build:
      context: .
      dockerfile: src/StokTakip/Customer/StokTakip.Customer.Api/Dockerfile
    ports:
        - "14002:5000"
        - "14003:5001"

